//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class measure_type
    {
        public measure_type()
        {
            this.measurements = new HashSet<measurement>();
            this.products = new HashSet<product>();
        }
    
        public int id { get; set; }
        public string measure_type1 { get; set; }
    
        public virtual ICollection<measurement> measurements { get; set; }
        public virtual ICollection<product> products { get; set; }
    }
}
