//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nutritional_value
    {
        public nutritional_value()
        {
            this.products_in_nutritional_value = new HashSet<products_in_nutritional_value>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int measurements_id { get; set; }
        public bool mustable { get; set; }
    
        public virtual measurement measurement { get; set; }
        public virtual ICollection<products_in_nutritional_value> products_in_nutritional_value { get; set; }
    }
}
