//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oracle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_in_nutritional_value
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public int nutritional_value_id { get; set; }
        public double amount_per_100 { get; set; }
    
        public virtual nutritional_value nutritional_value { get; set; }
        public virtual product product { get; set; }
    }
}
