//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oracle.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class recipeEntities : DbContext
    {
        public recipeEntities()
            : base("name=recipeEntities")
        {
            Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> categories { get; set; }
        public DbSet<equipment_in_recipe> equipment_in_recipe { get; set; }
        public DbSet<measure_type> measure_type { get; set; }
        public DbSet<measurement> measurements { get; set; }
        public DbSet<nutritional_value> nutritional_value { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<products_in_nutritional_value> products_in_nutritional_value { get; set; }
        public DbSet<products_in_recipe> products_in_recipe { get; set; }
        public DbSet<recipe> recipes { get; set; }
        public DbSet<recipe_for_user> recipe_for_user { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<measurement_with_type> measurement_with_type { get; set; }
        public DbSet<nutritional_value_details> nutritional_value_details { get; set; }
    }
}
